apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-postgres
  template:
    metadata:
      labels:
        app: tb-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "thingsboard"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tb-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: tb-postgres-data
      restartPolicy: Always