apiVersion: v1
kind: Service
metadata:
  name: thingsboard-ce
spec:
  selector:
    app: thingsboard-ce
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8080
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: internal
      protocol: TCP
      port: 7070
      targetPort: 7070
  type: ClusterIP  # LoadBalancer/NodePort for external access