apiVersion: apps/v1
kind: Deployment
metadata:
  name: thingsboard-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thingsboard-ce
  template:
    metadata:
      labels:
        app: thingsboard-ce
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z tb-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: thingsboard-ce
          image: thingsboard/tb-node:4.2.0
          ports:
            - containerPort: 8080
            - containerPort: 1883
            - containerPort: 7070
          env:
            - name: TB_SERVICE_ID
              value: "tb-ce-node"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tb-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://tb-postgres:5432/thingsboard"
          volumeMounts:
            - name: tb-data
              mountPath: /data
            - name: tb-logs
              mountPath: /var/log/thingsboard
      volumes:
        - name: tb-data
          persistentVolumeClaim:
            claimName: tb-data
        - name: tb-logs
          persistentVolumeClaim:
            claimName: tb-logs
      restartPolicy: Always