apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medplum-server
  template:
    metadata:
      labels:
        app: medplum-server
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z medplum-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: medplum-server
          image: medplum/medplum-server:4.3.12
          ports:
            - containerPort: 8103
          envFrom:
            - configMapRef:
                name: medplum-server-config
            - secretRef:
                name: medplum-postgres-secret
          command:
            - sh
            - -c
            - |
              echo 'No config file, running with env settings'
              node --require ./packages/server/dist/otel/instrumentation.js packages/server/dist/index.js env
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8103
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8103
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
      restartPolicy: Always