apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medplum-postgres
  template:
    metadata:
      labels:
        app: medplum-postgres
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: init-postgres-data
          image: busybox:1.28
          command: ['sh', '-c', 'chown -R 999:999 /var/lib/postgresql/data']
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: medplum-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "medplum"
#          command:
#            - "postgres"
#            - "-c"
#            - "listen_addresses=*"
#            - "-c"
#            - "statement_timeout=60000"
#            - "-c"
#            - "default_transaction_isolation=REPEATABLE READ"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medplum
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medplum
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: medplum-postgres-data
      restartPolicy: Always