# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  branches:
    dev:
      - step:
          name: Build and Deploy Backend
          condition:
            changesets:
              includePaths:
                - "apps/api/**"
          services:
            - docker
          script:
            # Set image TAG
            - IMAGE_TAG=$(echo $BITBUCKET_COMMIT | head -c7)

            # Build and push backend
            - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.digitalocean.com
            - docker build -f apps/api/Dockerfile -t registry.digitalocean.com/medboard-registry/api:$IMAGE_TAG .
            - docker push registry.digitalocean.com/medboard-registry/api:$IMAGE_TAG

            # Update API tag
            - sed -i "s#^\(\s*image:\s*registry\.digitalocean\.com/medboard-registry/api:\).*#\1$IMAGE_TAG#g" k8s/30-api.yaml

            # Deploy backend
            - pipe: atlassian/kubectl-run:3.12.0
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'k8s/30-api.yaml'

      - step:
          size: 2x
          name: Build and Deploy Frontend
          condition:
            changesets:
              includePaths:
                - "apps/front/**"
          services:
            - docker
          script:
            # Set image TAG
            - IMAGE_TAG=$(echo $BITBUCKET_COMMIT | head -c7)

            # Build and push frontend
            - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.digitalocean.com
            - docker build -f apps/front/Dockerfile -t registry.digitalocean.com/medboard-registry/front:$IMAGE_TAG .
            - docker push registry.digitalocean.com/medboard-registry/front:$IMAGE_TAG

            # Update Frontend tag
            - sed -i "s#^\(\s*image:\s*registry\.digitalocean\.com/medboard-registry/front:\).*#\1$IMAGE_TAG#g" k8s/32-frontend.yaml
            - grep -n "image:" k8s/32-frontend.yaml

            # Deploy frontend
            - pipe: atlassian/kubectl-run:3.12.0
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'k8s/32-frontend.yaml'

      - step:
          name: Deploy Kubernetes changes excluding frontend/api
          condition:
            changesets:
              includePaths:
                - "k8s/**"
          script:
            # Remove local job copies of frontend and api yaml files to avoid redeployment
            - rm -f k8s/30-api.yaml
            - rm -f k8s/32-frontend.yaml

            # Deploy other k8s resources
            - pipe: atlassian/kubectl-run:3.12.0
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'k8s/'