# thingsboard-ce
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard

---
# thingsboard-ce
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
# tb-postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
# medplum-postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medplum-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard