import { RuleNodeDefinition } from "@/types/ruleChainTypes";

/**
 * Catalogue of available rule-chain node types, grouped by category.
 * Colours mirror ThingsBoard's UI palette (yellow = Filter, green = Enrichment,
 * blue = Transformation, orange = Action, teal = Flow, red = External, purple = Analytics).
 */
export const RULE_NODE_DEFINITIONS: RuleNodeDefinition[] = [
  // ─── Filter ──────────────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.filter.TbCheckRelationNode",
    label: "check relation presence",
    category: "Filter",
    description: "Checks if a relation between entities exists.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbCheckMessageNode",
    label: "check fields presence",
    category: "Filter",
    description: "Checks if message fields are present.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbMsgTypeFilterNode",
    label: "message type filter",
    category: "Filter",
    description: "Filters messages by type.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbMsgTypeSwitchNode",
    label: "message type switch",
    category: "Filter",
    description: "Routes messages based on type.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbDeviceTypeFilterNode",
    label: "device profile switch",
    category: "Filter",
    description: "Routes based on device profile.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbEntityTypeFilterNode",
    label: "entity type filter",
    category: "Filter",
    description: "Filters by entity type.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbEntityTypeSwitchNode",
    label: "entity type switch",
    category: "Filter",
    description: "Switches flow by entity type.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbJsFilterNode",
    label: "script",
    category: "Filter",
    description: "Custom JS filter script.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbJsSwitchNode",
    label: "switch",
    category: "Filter",
    description: "Custom JS switch script.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbGpsGeoActionNode",
    label: "gps geofencing filter",
    category: "Filter",
    description: "Filters by GPS geofences.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbAssetProfileSwitchNode",
    label: "asset profile switch",
    category: "Filter",
    description: "Routes based on asset profile.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  {
    type: "org.thingsboard.rule.engine.filter.TbAlarmStatusFilterNode",
    label: "alarm status filter",
    category: "Filter",
    description: "Filters by alarm status.",
    color: "bg-yellow-300 dark:bg-yellow-500",
  },
  // ─── Enrichment ───────────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetAttributesNode",
    label: "originator attributes",
    category: "Enrichment",
    description: "Fetches originator attributes.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode",
    label: "originator fields",
    category: "Enrichment",
    description: "Fetches originator entity fields.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetTenantAttributeNode",
    label: "originator telemetry",
    category: "Enrichment",
    description: "Fetches originator telemetry.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetCustomerAttributeNode",
    label: "customer attributes",
    category: "Enrichment",
    description: "Fetches customer attributes.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetCustomerDetailNode",
    label: "customer details",
    category: "Enrichment",
    description: "Fetches customer details.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetDeviceAttrNode",
    label: "fetch device credentials",
    category: "Enrichment",
    description: "Fetches device credentials.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetTenantDetailsNode",
    label: "tenant details",
    category: "Enrichment",
    description: "Fetches tenant details.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbGetRelatedAttributeNode",
    label: "related device attributes",
    category: "Enrichment",
    description: "Fetches related entity attributes.",
    color: "bg-green-400 dark:bg-green-600",
  },
  {
    type: "org.thingsboard.rule.engine.metadata.TbCalculateDeltaNode",
    label: "calculate delta",
    category: "Enrichment",
    description: "Calculates delta between telemetry values.",
    color: "bg-green-400 dark:bg-green-600",
  },
  // ─── Transformation ───────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.transform.TbTransformMsgNode",
    label: "script",
    category: "Transformation",
    description: "Transforms message with a JS script.",
    color: "bg-blue-400 dark:bg-blue-600",
  },
  {
    type: "org.thingsboard.rule.engine.transform.TbChangeOriginatorNode",
    label: "change originator",
    category: "Transformation",
    description: "Changes the message originator.",
    color: "bg-blue-400 dark:bg-blue-600",
  },
  {
    type: "org.thingsboard.rule.engine.transform.TbMsgRenameKeyNode",
    label: "rename keys",
    category: "Transformation",
    description: "Renames message payload keys.",
    color: "bg-blue-400 dark:bg-blue-600",
  },
  {
    type: "org.thingsboard.rule.engine.transform.TbMsgDeleteKeysNode",
    label: "delete keys",
    category: "Transformation",
    description: "Deletes message payload keys.",
    color: "bg-blue-400 dark:bg-blue-600",
  },
  // ─── Action ───────────────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.action.TbSaveAttributesNode",
    label: "save attributes",
    category: "Action",
    description: "Saves attributes to entity.",
    color: "bg-orange-400 dark:bg-orange-600",
  },
  {
    type: "org.thingsboard.rule.engine.action.TbSaveTelemetryNode",
    label: "save timeseries",
    category: "Action",
    description: "Saves timeseries data.",
    color: "bg-orange-400 dark:bg-orange-600",
  },
  {
    type: "org.thingsboard.rule.engine.action.TbCreateAlarmNode",
    label: "create alarm",
    category: "Action",
    description: "Creates an alarm.",
    color: "bg-orange-400 dark:bg-orange-600",
  },
  {
    type: "org.thingsboard.rule.engine.action.TbClearAlarmNode",
    label: "clear alarm",
    category: "Action",
    description: "Clears an existing alarm.",
    color: "bg-orange-400 dark:bg-orange-600",
  },
  {
    type: "org.thingsboard.rule.engine.action.TbLogNode",
    label: "log",
    category: "Action",
    description: "Logs message to the platform log.",
    color: "bg-orange-400 dark:bg-orange-600",
  },
  // ─── External ─────────────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.rest.TbRestApiCallNode",
    label: "rest api call",
    category: "External",
    description: "Makes an outbound REST API call.",
    color: "bg-red-400 dark:bg-red-600",
  },
  {
    type: "org.thingsboard.rule.engine.mqtt.TbMqttNode",
    label: "mqtt",
    category: "External",
    description: "Sends message to an MQTT broker.",
    color: "bg-red-400 dark:bg-red-600",
  },
  {
    type: "org.thingsboard.rule.engine.kafka.TbKafkaNode",
    label: "kafka",
    category: "External",
    description: "Sends message to a Kafka topic.",
    color: "bg-red-400 dark:bg-red-600",
  },
  // ─── Flow ─────────────────────────────────────────────────────────────────
  {
    type: "org.thingsboard.rule.engine.flow.TbRuleChainInputNode",
    label: "rule chain",
    category: "Flow",
    description: "Routes message to another rule chain.",
    color: "bg-teal-400 dark:bg-teal-600",
  },
  {
    type: "org.thingsboard.rule.engine.flow.TbCheckpointNode",
    label: "checkpoint",
    category: "Flow",
    description: "Checkpoint node for acknowledgment.",
    color: "bg-teal-400 dark:bg-teal-600",
  },
];

/** All unique category names in display order */
export const RULE_NODE_CATEGORIES: RuleNodeDefinition["category"][] = [
  "Filter",
  "Enrichment",
  "Transformation",
  "Action",
  "External",
  "Flow",
];
