services:
  tb-gateway:
    image: thingsboard/tb-gateway:3.7-stable
    restart: always
    ports:
      - "5000:5000" # Comment if you don't use REST connector and change if you use another port
      # Uncomment and modify the following ports based on connector usage:
      #        - "1052:1052" # BACnet connector
      #        - "5026:5026" # Modbus TCP connector (Modbus Slave)
      #        - "50000:50000/tcp" # Socket connector with type TCP
      #        - "50000:50000/udp" # Socket connector with type UDP
    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - host=host.docker.internal
      - port=1883
      - accessToken=${GATEWAY_ACCESSTOKEN_ENV}

    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1884:1884"
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions