import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import SidebarLayout from "@/components/organisms/SidebarLayout";
import MedplumProviderWrapper from "@/lib/config/MedplumProviderWrapper";
import { TelemetryProvider } from "@/lib/context/TelemetryContext";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import StoreProvider from "./StoreProvider";
import WhitelabelLightColorsLoader from "@/components/organisms/WhitelabelLightColorsLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MedBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          id="whitelabel-light-colors"
          rel="stylesheet"
          href="/public-assets/global/light-colors.css?v=0"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <WhitelabelLightColorsLoader />
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange={false}
          >
            <MedplumProviderWrapper>
              <MantineProvider>
                <TelemetryProvider>
                  <SidebarLayout>{children}</SidebarLayout>
                </TelemetryProvider>
                <Toaster richColors theme="system" />
              </MantineProvider>
            </MedplumProviderWrapper>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
